### ISSUE TITLE
项目目录结构改造

### ISSUE THREAD

**Issue by linorwang** [kubesre/go-easy-admin#7]
![image](https://github.com/kubesre/go-easy-admin/assets/23013733/cf92a6eb-63d3-4dad-9058-df1f4af61d7d)
我个人觉得项目中接口不应该单独提取出来，而是放在对应的文件中例如users目录下，我们就应该放到把接口放到users.go文件中。

**Comment by zxl00** [comment]
是的，后面都有单独划分出来，这样写主要是为了让初学者更加易懂
